[2022-01-08 23:50:48,708] {scheduler_job.py:182} INFO - Started process (PID=60) to work on /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:50:48,712] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_orders_dataset.py for tasks to queue
[2022-01-08 23:50:48,730] {logging_mixin.py:104} INFO - [2022-01-08 23:50:48,730] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:50:50,353] {logging_mixin.py:104} INFO - [2022-01-08 23:50:50,347] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_orders_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_orders_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:50:50,357] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:50:50,378] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_orders_dataset.py took 1.674 seconds
[2022-01-08 23:51:27,828] {scheduler_job.py:182} INFO - Started process (PID=131) to work on /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:51:27,835] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_orders_dataset.py for tasks to queue
[2022-01-08 23:51:27,842] {logging_mixin.py:104} INFO - [2022-01-08 23:51:27,841] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:51:31,638] {logging_mixin.py:104} INFO - [2022-01-08 23:51:31,626] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_orders_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_orders_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:51:31,653] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:51:31,707] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_orders_dataset.py took 3.901 seconds
[2022-01-08 23:52:01,833] {scheduler_job.py:182} INFO - Started process (PID=171) to work on /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:52:01,838] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_orders_dataset.py for tasks to queue
[2022-01-08 23:52:01,842] {logging_mixin.py:104} INFO - [2022-01-08 23:52:01,841] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:52:03,261] {logging_mixin.py:104} INFO - [2022-01-08 23:52:03,255] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_orders_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_orders_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:52:03,265] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:52:03,285] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_orders_dataset.py took 1.460 seconds
[2022-01-08 23:52:33,949] {scheduler_job.py:182} INFO - Started process (PID=211) to work on /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:52:33,954] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_orders_dataset.py for tasks to queue
[2022-01-08 23:52:33,956] {logging_mixin.py:104} INFO - [2022-01-08 23:52:33,956] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:52:35,583] {logging_mixin.py:104} INFO - [2022-01-08 23:52:35,577] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_orders_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_orders_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:52:35,586] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:52:35,605] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_orders_dataset.py took 1.661 seconds
[2022-01-08 23:53:05,986] {scheduler_job.py:182} INFO - Started process (PID=251) to work on /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:53:05,993] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_orders_dataset.py for tasks to queue
[2022-01-08 23:53:05,996] {logging_mixin.py:104} INFO - [2022-01-08 23:53:05,996] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:53:07,380] {logging_mixin.py:104} INFO - [2022-01-08 23:53:07,375] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_orders_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_orders_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:53:07,383] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:53:07,403] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_orders_dataset.py took 1.427 seconds
[2022-01-08 23:53:38,019] {scheduler_job.py:182} INFO - Started process (PID=291) to work on /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:53:38,025] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_orders_dataset.py for tasks to queue
[2022-01-08 23:53:38,028] {logging_mixin.py:104} INFO - [2022-01-08 23:53:38,028] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:53:39,504] {logging_mixin.py:104} INFO - [2022-01-08 23:53:39,499] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_orders_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_orders_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:53:39,508] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:53:39,525] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_orders_dataset.py took 1.515 seconds
[2022-01-08 23:54:10,619] {scheduler_job.py:182} INFO - Started process (PID=331) to work on /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:54:10,629] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_orders_dataset.py for tasks to queue
[2022-01-08 23:54:10,633] {logging_mixin.py:104} INFO - [2022-01-08 23:54:10,633] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:54:12,136] {logging_mixin.py:104} INFO - [2022-01-08 23:54:12,131] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_orders_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_orders_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:54:12,142] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:54:12,163] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_orders_dataset.py took 1.554 seconds
[2022-01-08 23:54:43,005] {scheduler_job.py:182} INFO - Started process (PID=371) to work on /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:54:43,009] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_orders_dataset.py for tasks to queue
[2022-01-08 23:54:43,012] {logging_mixin.py:104} INFO - [2022-01-08 23:54:43,012] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:54:44,502] {logging_mixin.py:104} INFO - [2022-01-08 23:54:44,496] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_orders_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_orders_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:54:44,506] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:54:44,525] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_orders_dataset.py took 1.527 seconds
[2022-01-08 23:55:14,748] {scheduler_job.py:182} INFO - Started process (PID=411) to work on /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:55:14,754] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_orders_dataset.py for tasks to queue
[2022-01-08 23:55:14,758] {logging_mixin.py:104} INFO - [2022-01-08 23:55:14,757] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:55:16,589] {logging_mixin.py:104} INFO - [2022-01-08 23:55:16,579] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_orders_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_orders_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:55:16,598] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:55:16,635] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_orders_dataset.py took 1.907 seconds
[2022-01-08 23:55:47,468] {scheduler_job.py:182} INFO - Started process (PID=451) to work on /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:55:47,474] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_orders_dataset.py for tasks to queue
[2022-01-08 23:55:47,477] {logging_mixin.py:104} INFO - [2022-01-08 23:55:47,477] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:55:49,008] {logging_mixin.py:104} INFO - [2022-01-08 23:55:49,002] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_orders_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_orders_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:55:49,011] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:55:49,033] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_orders_dataset.py took 1.574 seconds
[2022-01-08 23:56:19,678] {scheduler_job.py:182} INFO - Started process (PID=491) to work on /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:56:19,685] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_orders_dataset.py for tasks to queue
[2022-01-08 23:56:19,688] {logging_mixin.py:104} INFO - [2022-01-08 23:56:19,688] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:56:21,091] {logging_mixin.py:104} INFO - [2022-01-08 23:56:21,085] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_orders_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_orders_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:56:21,094] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:56:21,114] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_orders_dataset.py took 1.445 seconds
[2022-01-08 23:56:51,704] {scheduler_job.py:182} INFO - Started process (PID=531) to work on /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:56:51,710] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_orders_dataset.py for tasks to queue
[2022-01-08 23:56:51,713] {logging_mixin.py:104} INFO - [2022-01-08 23:56:51,712] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:56:53,344] {logging_mixin.py:104} INFO - [2022-01-08 23:56:53,332] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_orders_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_orders_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:56:53,355] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:56:53,378] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_orders_dataset.py took 1.685 seconds
[2022-01-08 23:57:23,819] {scheduler_job.py:182} INFO - Started process (PID=571) to work on /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:57:23,825] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_orders_dataset.py for tasks to queue
[2022-01-08 23:57:23,829] {logging_mixin.py:104} INFO - [2022-01-08 23:57:23,828] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:57:25,529] {logging_mixin.py:104} INFO - [2022-01-08 23:57:25,521] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_orders_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_orders_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:57:25,533] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:57:25,561] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_orders_dataset.py took 1.758 seconds
[2022-01-08 23:57:56,366] {scheduler_job.py:182} INFO - Started process (PID=611) to work on /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:57:56,375] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_orders_dataset.py for tasks to queue
[2022-01-08 23:57:56,378] {logging_mixin.py:104} INFO - [2022-01-08 23:57:56,378] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:57:58,014] {logging_mixin.py:104} INFO - [2022-01-08 23:57:57,988] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_orders_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_orders_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:57:58,018] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:57:58,040] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_orders_dataset.py took 1.687 seconds
[2022-01-08 23:58:28,229] {scheduler_job.py:182} INFO - Started process (PID=651) to work on /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:58:28,234] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_orders_dataset.py for tasks to queue
[2022-01-08 23:58:28,236] {logging_mixin.py:104} INFO - [2022-01-08 23:58:28,236] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:58:29,720] {logging_mixin.py:104} INFO - [2022-01-08 23:58:29,715] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_orders_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_orders_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:58:29,725] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:58:29,744] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_orders_dataset.py took 1.522 seconds
[2022-01-08 23:58:59,923] {scheduler_job.py:182} INFO - Started process (PID=691) to work on /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:58:59,930] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_orders_dataset.py for tasks to queue
[2022-01-08 23:58:59,934] {logging_mixin.py:104} INFO - [2022-01-08 23:58:59,933] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:59:01,461] {logging_mixin.py:104} INFO - [2022-01-08 23:59:01,455] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_orders_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_orders_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:59:01,466] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:59:01,486] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_orders_dataset.py took 1.572 seconds
[2022-01-08 23:59:31,600] {scheduler_job.py:182} INFO - Started process (PID=731) to work on /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:59:31,607] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_orders_dataset.py for tasks to queue
[2022-01-08 23:59:31,611] {logging_mixin.py:104} INFO - [2022-01-08 23:59:31,610] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:59:33,317] {logging_mixin.py:104} INFO - [2022-01-08 23:59:33,312] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_orders_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_orders_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:59:33,323] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_orders_dataset.py
[2022-01-08 23:59:33,344] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_orders_dataset.py took 1.750 seconds
