[2022-01-08 23:50:43,881] {scheduler_job.py:182} INFO - Started process (PID=50) to work on /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:50:43,884] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_sellers_dataset.py for tasks to queue
[2022-01-08 23:50:43,887] {logging_mixin.py:104} INFO - [2022-01-08 23:50:43,887] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:50:45,465] {logging_mixin.py:104} INFO - [2022-01-08 23:50:45,459] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_sellers_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_sellers_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:50:45,469] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:50:45,491] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_sellers_dataset.py took 1.615 seconds
[2022-01-08 23:51:16,316] {scheduler_job.py:182} INFO - Started process (PID=117) to work on /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:51:16,328] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_sellers_dataset.py for tasks to queue
[2022-01-08 23:51:16,335] {logging_mixin.py:104} INFO - [2022-01-08 23:51:16,335] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:51:19,651] {logging_mixin.py:104} INFO - [2022-01-08 23:51:19,638] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_sellers_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_sellers_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:51:19,662] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:51:19,720] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_sellers_dataset.py took 3.417 seconds
[2022-01-08 23:51:50,879] {scheduler_job.py:182} INFO - Started process (PID=161) to work on /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:51:50,884] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_sellers_dataset.py for tasks to queue
[2022-01-08 23:51:50,887] {logging_mixin.py:104} INFO - [2022-01-08 23:51:50,887] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:51:52,283] {logging_mixin.py:104} INFO - [2022-01-08 23:51:52,277] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_sellers_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_sellers_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:51:52,286] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:51:52,306] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_sellers_dataset.py took 1.434 seconds
[2022-01-08 23:52:22,628] {scheduler_job.py:182} INFO - Started process (PID=201) to work on /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:52:22,634] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_sellers_dataset.py for tasks to queue
[2022-01-08 23:52:22,637] {logging_mixin.py:104} INFO - [2022-01-08 23:52:22,637] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:52:24,027] {logging_mixin.py:104} INFO - [2022-01-08 23:52:24,022] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_sellers_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_sellers_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:52:24,031] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:52:24,050] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_sellers_dataset.py took 1.430 seconds
[2022-01-08 23:52:54,631] {scheduler_job.py:182} INFO - Started process (PID=241) to work on /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:52:54,635] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_sellers_dataset.py for tasks to queue
[2022-01-08 23:52:54,637] {logging_mixin.py:104} INFO - [2022-01-08 23:52:54,637] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:52:56,018] {logging_mixin.py:104} INFO - [2022-01-08 23:52:56,013] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_sellers_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_sellers_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:52:56,022] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:52:56,040] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_sellers_dataset.py took 1.413 seconds
[2022-01-08 23:53:26,671] {scheduler_job.py:182} INFO - Started process (PID=281) to work on /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:53:26,678] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_sellers_dataset.py for tasks to queue
[2022-01-08 23:53:26,682] {logging_mixin.py:104} INFO - [2022-01-08 23:53:26,681] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:53:28,059] {logging_mixin.py:104} INFO - [2022-01-08 23:53:28,053] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_sellers_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_sellers_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:53:28,064] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:53:28,083] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_sellers_dataset.py took 1.421 seconds
[2022-01-08 23:53:58,235] {scheduler_job.py:182} INFO - Started process (PID=321) to work on /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:53:58,242] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_sellers_dataset.py for tasks to queue
[2022-01-08 23:53:58,247] {logging_mixin.py:104} INFO - [2022-01-08 23:53:58,247] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:53:59,711] {logging_mixin.py:104} INFO - [2022-01-08 23:53:59,706] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_sellers_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_sellers_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:53:59,715] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:53:59,734] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_sellers_dataset.py took 1.509 seconds
[2022-01-08 23:54:30,618] {scheduler_job.py:182} INFO - Started process (PID=361) to work on /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:54:30,624] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_sellers_dataset.py for tasks to queue
[2022-01-08 23:54:30,627] {logging_mixin.py:104} INFO - [2022-01-08 23:54:30,626] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:54:32,115] {logging_mixin.py:104} INFO - [2022-01-08 23:54:32,109] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_sellers_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_sellers_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:54:32,118] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:54:32,138] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_sellers_dataset.py took 1.528 seconds
[2022-01-08 23:55:04,344] {scheduler_job.py:182} INFO - Started process (PID=401) to work on /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:55:04,350] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_sellers_dataset.py for tasks to queue
[2022-01-08 23:55:04,354] {logging_mixin.py:104} INFO - [2022-01-08 23:55:04,353] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:55:06,028] {logging_mixin.py:104} INFO - [2022-01-08 23:55:06,021] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_sellers_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_sellers_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:55:06,033] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:55:06,059] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_sellers_dataset.py took 1.724 seconds
[2022-01-08 23:55:37,258] {scheduler_job.py:182} INFO - Started process (PID=441) to work on /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:55:37,265] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_sellers_dataset.py for tasks to queue
[2022-01-08 23:55:37,268] {logging_mixin.py:104} INFO - [2022-01-08 23:55:37,268] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:55:38,722] {logging_mixin.py:104} INFO - [2022-01-08 23:55:38,717] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_sellers_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_sellers_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:55:38,726] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:55:38,748] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_sellers_dataset.py took 1.498 seconds
[2022-01-08 23:56:09,512] {scheduler_job.py:182} INFO - Started process (PID=481) to work on /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:56:09,520] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_sellers_dataset.py for tasks to queue
[2022-01-08 23:56:09,523] {logging_mixin.py:104} INFO - [2022-01-08 23:56:09,523] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:56:10,992] {logging_mixin.py:104} INFO - [2022-01-08 23:56:10,986] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_sellers_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_sellers_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:56:10,995] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:56:11,016] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_sellers_dataset.py took 1.513 seconds
[2022-01-08 23:56:41,211] {scheduler_job.py:182} INFO - Started process (PID=521) to work on /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:56:41,218] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_sellers_dataset.py for tasks to queue
[2022-01-08 23:56:41,221] {logging_mixin.py:104} INFO - [2022-01-08 23:56:41,221] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:56:42,735] {logging_mixin.py:104} INFO - [2022-01-08 23:56:42,729] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_sellers_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_sellers_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:56:42,740] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:56:42,761] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_sellers_dataset.py took 1.560 seconds
[2022-01-08 23:57:13,889] {scheduler_job.py:182} INFO - Started process (PID=561) to work on /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:57:13,899] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_sellers_dataset.py for tasks to queue
[2022-01-08 23:57:13,905] {logging_mixin.py:104} INFO - [2022-01-08 23:57:13,905] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:57:16,143] {logging_mixin.py:104} INFO - [2022-01-08 23:57:16,134] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_sellers_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_sellers_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:57:16,147] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:57:16,178] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_sellers_dataset.py took 2.308 seconds
[2022-01-08 23:57:47,375] {scheduler_job.py:182} INFO - Started process (PID=601) to work on /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:57:47,381] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_sellers_dataset.py for tasks to queue
[2022-01-08 23:57:47,384] {logging_mixin.py:104} INFO - [2022-01-08 23:57:47,384] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:57:49,118] {logging_mixin.py:104} INFO - [2022-01-08 23:57:49,110] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_sellers_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_sellers_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:57:49,122] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:57:49,144] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_sellers_dataset.py took 1.784 seconds
[2022-01-08 23:58:20,344] {scheduler_job.py:182} INFO - Started process (PID=641) to work on /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:58:20,350] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_sellers_dataset.py for tasks to queue
[2022-01-08 23:58:20,354] {logging_mixin.py:104} INFO - [2022-01-08 23:58:20,354] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:58:21,947] {logging_mixin.py:104} INFO - [2022-01-08 23:58:21,940] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_sellers_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_sellers_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:58:21,953] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:58:21,976] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_sellers_dataset.py took 1.646 seconds
[2022-01-08 23:58:53,036] {scheduler_job.py:182} INFO - Started process (PID=681) to work on /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:58:53,041] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_sellers_dataset.py for tasks to queue
[2022-01-08 23:58:53,044] {logging_mixin.py:104} INFO - [2022-01-08 23:58:53,044] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:58:54,576] {logging_mixin.py:104} INFO - [2022-01-08 23:58:54,568] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_sellers_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_sellers_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:58:54,580] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:58:54,616] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_sellers_dataset.py took 1.588 seconds
[2022-01-08 23:59:25,760] {scheduler_job.py:182} INFO - Started process (PID=721) to work on /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:59:25,765] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_sellers_dataset.py for tasks to queue
[2022-01-08 23:59:25,770] {logging_mixin.py:104} INFO - [2022-01-08 23:59:25,769] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:59:27,474] {logging_mixin.py:104} INFO - [2022-01-08 23:59:27,467] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_sellers_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_sellers_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:59:27,482] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:59:27,507] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_sellers_dataset.py took 1.755 seconds
[2022-01-08 23:59:58,041] {scheduler_job.py:182} INFO - Started process (PID=761) to work on /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:59:58,046] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_sellers_dataset.py for tasks to queue
[2022-01-08 23:59:58,050] {logging_mixin.py:104} INFO - [2022-01-08 23:59:58,049] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:59:59,503] {logging_mixin.py:104} INFO - [2022-01-08 23:59:59,497] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_sellers_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_sellers_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:59:59,507] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_sellers_dataset.py
[2022-01-08 23:59:59,527] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_sellers_dataset.py took 1.495 seconds
