[2022-01-08 23:50:57,093] {scheduler_job.py:182} INFO - Started process (PID=76) to work on /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:50:57,097] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_order_items_dataset.py for tasks to queue
[2022-01-08 23:50:57,099] {logging_mixin.py:104} INFO - [2022-01-08 23:50:57,099] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:50:58,658] {logging_mixin.py:104} INFO - [2022-01-08 23:50:58,652] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_order_items_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_order_items_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:50:58,662] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:50:58,685] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_order_items_dataset.py took 1.596 seconds
[2022-01-08 23:51:40,955] {scheduler_job.py:182} INFO - Started process (PID=146) to work on /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:51:40,968] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_order_items_dataset.py for tasks to queue
[2022-01-08 23:51:40,971] {logging_mixin.py:104} INFO - [2022-01-08 23:51:40,971] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:51:43,208] {logging_mixin.py:104} INFO - [2022-01-08 23:51:43,203] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_order_items_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_order_items_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:51:43,211] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:51:43,237] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_order_items_dataset.py took 2.288 seconds
[2022-01-08 23:52:13,524] {scheduler_job.py:182} INFO - Started process (PID=186) to work on /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:52:13,529] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_order_items_dataset.py for tasks to queue
[2022-01-08 23:52:13,532] {logging_mixin.py:104} INFO - [2022-01-08 23:52:13,531] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:52:14,922] {logging_mixin.py:104} INFO - [2022-01-08 23:52:14,917] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_order_items_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_order_items_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:52:14,925] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:52:14,945] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_order_items_dataset.py took 1.429 seconds
[2022-01-08 23:52:45,731] {scheduler_job.py:182} INFO - Started process (PID=226) to work on /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:52:45,739] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_order_items_dataset.py for tasks to queue
[2022-01-08 23:52:45,742] {logging_mixin.py:104} INFO - [2022-01-08 23:52:45,741] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:52:47,120] {logging_mixin.py:104} INFO - [2022-01-08 23:52:47,116] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_order_items_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_order_items_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:52:47,124] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:52:47,142] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_order_items_dataset.py took 1.419 seconds
[2022-01-08 23:53:17,770] {scheduler_job.py:182} INFO - Started process (PID=266) to work on /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:53:17,775] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_order_items_dataset.py for tasks to queue
[2022-01-08 23:53:17,778] {logging_mixin.py:104} INFO - [2022-01-08 23:53:17,778] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:53:19,185] {logging_mixin.py:104} INFO - [2022-01-08 23:53:19,179] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_order_items_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_order_items_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:53:19,188] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:53:19,207] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_order_items_dataset.py took 1.446 seconds
[2022-01-08 23:53:50,120] {scheduler_job.py:182} INFO - Started process (PID=306) to work on /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:53:50,128] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_order_items_dataset.py for tasks to queue
[2022-01-08 23:53:50,131] {logging_mixin.py:104} INFO - [2022-01-08 23:53:50,131] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:53:51,865] {logging_mixin.py:104} INFO - [2022-01-08 23:53:51,859] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_order_items_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_order_items_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:53:51,872] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:53:51,896] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_order_items_dataset.py took 1.782 seconds
[2022-01-08 23:54:22,423] {scheduler_job.py:182} INFO - Started process (PID=346) to work on /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:54:22,428] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_order_items_dataset.py for tasks to queue
[2022-01-08 23:54:22,431] {logging_mixin.py:104} INFO - [2022-01-08 23:54:22,431] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:54:24,075] {logging_mixin.py:104} INFO - [2022-01-08 23:54:24,067] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_order_items_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_order_items_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:54:24,080] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:54:24,109] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_order_items_dataset.py took 1.694 seconds
[2022-01-08 23:54:55,025] {scheduler_job.py:182} INFO - Started process (PID=386) to work on /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:54:55,030] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_order_items_dataset.py for tasks to queue
[2022-01-08 23:54:55,033] {logging_mixin.py:104} INFO - [2022-01-08 23:54:55,033] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:54:56,637] {logging_mixin.py:104} INFO - [2022-01-08 23:54:56,629] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_order_items_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_order_items_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:54:56,644] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:54:56,672] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_order_items_dataset.py took 1.657 seconds
[2022-01-08 23:55:26,914] {scheduler_job.py:182} INFO - Started process (PID=426) to work on /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:55:26,919] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_order_items_dataset.py for tasks to queue
[2022-01-08 23:55:26,922] {logging_mixin.py:104} INFO - [2022-01-08 23:55:26,922] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:55:28,407] {logging_mixin.py:104} INFO - [2022-01-08 23:55:28,402] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_order_items_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_order_items_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:55:28,411] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:55:28,431] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_order_items_dataset.py took 1.524 seconds
[2022-01-08 23:55:58,984] {scheduler_job.py:182} INFO - Started process (PID=466) to work on /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:55:58,990] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_order_items_dataset.py for tasks to queue
[2022-01-08 23:55:58,993] {logging_mixin.py:104} INFO - [2022-01-08 23:55:58,993] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:56:00,440] {logging_mixin.py:104} INFO - [2022-01-08 23:56:00,435] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_order_items_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_order_items_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:56:00,444] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:56:00,465] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_order_items_dataset.py took 1.490 seconds
[2022-01-08 23:56:31,508] {scheduler_job.py:182} INFO - Started process (PID=506) to work on /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:56:31,513] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_order_items_dataset.py for tasks to queue
[2022-01-08 23:56:31,515] {logging_mixin.py:104} INFO - [2022-01-08 23:56:31,515] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:56:33,260] {logging_mixin.py:104} INFO - [2022-01-08 23:56:33,253] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_order_items_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_order_items_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:56:33,264] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:56:33,289] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_order_items_dataset.py took 1.788 seconds
[2022-01-08 23:57:03,585] {scheduler_job.py:182} INFO - Started process (PID=546) to work on /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:57:03,591] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_order_items_dataset.py for tasks to queue
[2022-01-08 23:57:03,594] {logging_mixin.py:104} INFO - [2022-01-08 23:57:03,594] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:57:05,179] {logging_mixin.py:104} INFO - [2022-01-08 23:57:05,174] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_order_items_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_order_items_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:57:05,184] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:57:05,205] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_order_items_dataset.py took 1.628 seconds
[2022-01-08 23:57:35,786] {scheduler_job.py:182} INFO - Started process (PID=586) to work on /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:57:35,793] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_order_items_dataset.py for tasks to queue
[2022-01-08 23:57:35,797] {logging_mixin.py:104} INFO - [2022-01-08 23:57:35,796] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:57:37,296] {logging_mixin.py:104} INFO - [2022-01-08 23:57:37,290] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_order_items_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_order_items_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:57:37,299] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:57:37,319] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_order_items_dataset.py took 1.544 seconds
[2022-01-08 23:58:08,388] {scheduler_job.py:182} INFO - Started process (PID=626) to work on /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:58:08,395] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_order_items_dataset.py for tasks to queue
[2022-01-08 23:58:08,398] {logging_mixin.py:104} INFO - [2022-01-08 23:58:08,398] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:58:09,905] {logging_mixin.py:104} INFO - [2022-01-08 23:58:09,898] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_order_items_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_order_items_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:58:09,909] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:58:09,929] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_order_items_dataset.py took 1.549 seconds
[2022-01-08 23:58:40,176] {scheduler_job.py:182} INFO - Started process (PID=666) to work on /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:58:40,183] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_order_items_dataset.py for tasks to queue
[2022-01-08 23:58:40,188] {logging_mixin.py:104} INFO - [2022-01-08 23:58:40,187] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:58:41,714] {logging_mixin.py:104} INFO - [2022-01-08 23:58:41,708] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_order_items_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_order_items_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:58:41,718] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:58:41,738] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_order_items_dataset.py took 1.572 seconds
[2022-01-08 23:59:12,720] {scheduler_job.py:182} INFO - Started process (PID=706) to work on /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:59:12,725] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_order_items_dataset.py for tasks to queue
[2022-01-08 23:59:12,737] {logging_mixin.py:104} INFO - [2022-01-08 23:59:12,737] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:59:14,275] {logging_mixin.py:104} INFO - [2022-01-08 23:59:14,267] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_order_items_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_order_items_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:59:14,279] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:59:14,303] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_order_items_dataset.py took 1.591 seconds
[2022-01-08 23:59:44,790] {scheduler_job.py:182} INFO - Started process (PID=746) to work on /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:59:44,796] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/ETL_olist_order_items_dataset.py for tasks to queue
[2022-01-08 23:59:44,799] {logging_mixin.py:104} INFO - [2022-01-08 23:59:44,798] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:59:46,522] {logging_mixin.py:104} INFO - [2022-01-08 23:59:46,515] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/ETL_olist_order_items_dataset.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ETL_olist_order_items_dataset.py", line 5, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2022-01-08 23:59:46,528] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/ETL_olist_order_items_dataset.py
[2022-01-08 23:59:46,552] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/ETL_olist_order_items_dataset.py took 1.770 seconds
